window.HiveMindModule = Object.freeze({
  schemaVersion: 1,
  id: 'aircraft-performance',
  title: 'Aircraft Performance',
  description: 'A five-layer dependency map from forces and equilibrium through operational and high-speed limits.',
  layers: [
    {
      id:'l1', num:'01', title:'Forces & Equilibrium',
      sub:'Before any performance can be discussed, the aircraft must be flying. Four forces in balance define the null state — every performance deviation is measured from here.',
      nodes:[
        {id:'lift', label:'LIFT', sub:'½ρV²SC_L', r:1,c:'1/2', tag:'', math:'L', formula:'L = \\tfrac{1}{2}\\rho V^2 S C_L', detail:'Aerodynamic force perpendicular to the flight path. The wing deflects airflow downward; Newton\'s third law pushes the aircraft up. Lift is the mechanism that converts forward motion into sustained flight.', mistake:'Assuming L = W always. This equality only holds in unaccelerated level flight — not in climbs, descents, or turns.', interview:'If an aircraft banks 60° in a coordinated turn at constant altitude, by how much does lift increase and why?'},
        {id:'drag', label:'DRAG', sub:'D_i + D_p', r:1,c:'2/3', tag:'', formula:'D = \\tfrac{1}{2}\\rho V^2 S C_D', detail:'Aerodynamic force opposing motion. Induced drag decreases with V²; parasite drag increases with V². Their sum produces the characteristic U-shaped drag curve — the backbone of every performance diagram.', mistake:'Treating drag as a single entity. The two components behave oppositely with speed, which is why there is a minimum-drag speed.', interview:'How does drag change when an aircraft climbs at constant indicated airspeed?'},
        {id:'weight', label:'WEIGHT', sub:'mg — always downward',r:1,c:'3/4', tag:'', formula:'W = mg', detail:'The only force that never stops. Every performance metric — takeoff distance, ceiling, range, climb rate — degrades as weight increases. As fuel burns, weight decreases; smart operations exploit this continuously.', mistake:'Treating weight as constant through a flight. A long-haul aircraft may burn 40% of its gross weight in fuel — the aircraft in cruise is fundamentally different from the aircraft at brake release.', interview:'An aircraft burns 10 t of fuel on a long sector. How does this change optimum cruise altitude?'},
        {id:'thrust', label:'THRUST', sub:'T = ṁ(V_e − V₀)', r:1,c:'4/5', tag:'', formula:'T = \\dot{m}(V_e - V_0)', detail:'Propulsive force from the engine. Thrust available decreases with altitude as air density falls. The gap between thrust available and thrust required is the single source of all climb and acceleration capability.', mistake:'Confusing thrust and power. Thrust is force. Power is force × velocity. High thrust at low speed ≠ high power.', interview:'Why does available thrust decrease with altitude, and what happens to the thrust required curve?'},
        {id:'lvlflt', label:'LEVEL FLIGHT', sub:'L = W,  T = D', r:2,c:'2/4', tag:'', formula:'L = W \\qquad T = D', detail:'The baseline. Steady level unaccelerated flight is the reference state for all performance analysis. All performance metrics are either deviations from or conditions derived from this equilibrium.', mistake:'Thinking level flight means zero performance effort. The aircraft is working constantly — just at equilibrium. Excess is what enables everything else.', interview:'What does "steady level flight" actually mean, and why is it the reference point for all performance calculations?'},
      ],
      edges:[['lift','lvlflt'],['drag','lvlflt'],['weight','lvlflt'],['thrust','lvlflt']]
    },
    {
      id:'l2', num:'02', title:'Energy & Performance Foundations',
      sub:'What allows the aircraft to do more than maintain level flight? Excess — thrust or power above equilibrium — is the origin of every performance metric that follows. This layer is the heart of the map.',
      nodes:[
        {id:'treq', label:'THRUST REQUIRED', sub:'= drag curve', r:1,c:'1/3', tag:'', formula:'T_{req} = D = \\tfrac{1}{2}\\rho V^2 S C_D', detail:'At each airspeed, thrust required equals drag. The shape of this curve determines minimum-drag speed, best L/D, and every performance-optimal speed. The minimum occurs at (L/D)_max.', mistake:'Confusing thrust required with power required. They share the same minimum-drag point but produce different optimal speeds for other tasks.', interview:'Why does the thrust required curve have a U-shape, and what does each side represent?'},
        {id:'tavail', label:'THRUST AVAILABLE', sub:'drops with altitude', r:1,c:'3/5', tag:'', formula:'T_{avail} \\approx T_{SL}\\cdot\\frac{\\rho}{\\rho_0}', detail:'The engine\'s output at a given altitude and throttle. As density falls with altitude, thrust available falls too. The intersection of thrust available and thrust required curves defines maximum level speed and, as they converge, the absolute ceiling.', mistake:'Assuming constant thrust with altitude. Above the tropopause the density gradient changes and so does the thrust lapse rate.', interview:'What two curves intersect to define the absolute ceiling of a jet aircraft?'},
        {id:'preq', label:'POWER REQUIRED', sub:'= drag × velocity', r:2,c:'1/3', tag:'', formula:'P_{req} = D \\cdot V', detail:'Power required shifts the analysis from force to energy rate. The minimum of the power curve occurs at a speed slower than minimum drag — Vmp < Vmd. This is critical: best endurance speed ≠ best range speed.', mistake:'Assuming minimum power speed = minimum drag speed. They are always different: Vmp ≈ 0.76 × Vmd for a parabolic polar.', interview:'Why is the speed for minimum power required always lower than the speed for minimum drag?'},
        {id:'pavail', label:'POWER AVAILABLE', sub:'T × TAS', r:2,c:'3/5', tag:'', formula:'P_{avail} = T_{avail} \\cdot V', detail:'Power available can initially increase with altitude at constant IAS, because TAS rises even as thrust falls. This makes power analysis more nuanced than thrust analysis across the altitude envelope.', mistake:'Thinking power available always decreases monotonically with altitude at constant IAS. The TAS factor means it is more complex.', interview:'What happens to power available as a jet climbs at constant indicated airspeed?'},
        {id:'exthrust',label:'EXCESS THRUST', sub:'T_avail − T_req', r:3,c:'1/3', tag:'', formula:'\\Delta T = T_{avail} - T_{req}', detail:'The force margin above what level flight demands. Excess thrust determines climb angle — the steepness of the flight path. At best angle of climb speed (Vx), excess thrust is maximized.', mistake:'Using excess thrust to calculate rate of climb. Rate of climb uses excess power; excess thrust gives angle of climb. Confusing the two leads to the wrong speed selection.', interview:'An aircraft has maximum excess thrust at 140 kt. At what speed should it fly for best angle of climb?'},
        {id:'expow', label:'EXCESS POWER', sub:'P_avail − P_req', r:3,c:'3/5', tag:'work', formula:'P_{ex} = P_{avail} - P_{req} = W \\cdot ROC', detail:'The master variable of Aircraft Performance. Excess power is the energy rate the aircraft possesses beyond what equilibrium demands. It can be converted to altitude gain (rate of climb) or speed increase. Every metric in layers 3–5 traces back to this one quantity.', mistake:'Confusing excess power with excess thrust. They are related but distinct — they lead to different optimal speeds and different performance metrics.', interview:'Derive the relationship between excess power and rate of climb from energy principles. Why does ROC use excess power rather than excess thrust?'},
      ],
      edges:[['treq','exthrust'],['tavail','exthrust'],['preq','expow'],['pavail','expow'],['exthrust','expow',1]]
    },
    {
      id:'l3', num:'03', title:'Performance Modes',
      sub:'How an aircraft deliberately spends energy. Each mode is a directed allocation of the excess established in Layer 2 toward a defined objective — altitude, distance, time, or turning.',
      nodes:[
        {id:'roc', label:'RATE OF CLIMB', sub:'excess power / weight',r:1,c:'1/2', tag:'work', formula:'ROC = \\frac{P_{ex}}{W} = V\\sin\\gamma', detail:'The aircraft climbs because it has power beyond what level flight demands. Best rate speed (Vy) is the speed of maximum excess power — always higher than Vx. Determines certification gradients and time-to-climb.', mistake:'Flying Vx (best angle) when you want best rate. Vx maximizes height per distance; Vy maximizes height per time. They serve different purposes.', interview:'Why are Vx and Vy different speeds, and when would you use each?'},
        {id:'aoc', label:'ANGLE OF CLIMB', sub:'excess thrust / weight',r:1,c:'2/3', formula:'\\sin\\gamma = \\frac{T-D}{W}', detail:'Steepness of the flight path. Critical for obstacle clearance after takeoff. Best angle of climb (Vx) maximizes height per horizontal distance. SID procedures define minimum required climb gradients that the aircraft must meet.', mistake:'Assuming higher speed always gives better angle. More speed increases parasite drag, reducing excess thrust and therefore angle of climb.', interview:'An SID requires 200 ft/nm gradient. How do you verify the aircraft can comply at the given weight and density altitude?'},
        {id:'ld', label:'L/D RATIO', sub:'aerodynamic efficiency',r:1,c:'3/5', formula:'\\frac{L}{D} = \\frac{C_L}{C_D}', detail:'The single most important aerodynamic efficiency number. Maximum L/D speed is best glide speed and also best range speed for a jet (roughly). It appears directly in the Breguet range equation and governs fuel efficiency across all phases.', mistake:'Thinking L/D is purely a cruise metric. It governs climb, descent, glide, and range equally — it is the aerodynamic efficiency of the whole aircraft.', interview:'Where does maximum L/D appear in the thrust required curve, and why?'},
        {id:'specrange',label:'SPECIFIC RANGE',sub:'distance per kg fuel',r:2,c:'1/2', tag:'work', formula:'SR = \\frac{V}{\\dot{W}_f} = \\frac{V}{TSFC \\cdot T}', detail:'Nautical miles per kilogram of fuel — the cruise efficiency metric. Speed that maximises SR is maximum range cruise. SR decreases as weight decreases, so the optimal cruise speed and altitude change continuously during a sector.', mistake:'Assuming maximum SR = maximum speed. Higher speed increases drag non-linearly, reducing SR significantly.', interview:'How does specific range change as fuel burns during cruise, and what operational technique exploits this?'},
        {id:'loadf', label:'LOAD FACTOR', sub:'L/W — structural multiplier',r:2,c:'2/3', tag:'work', formula:'n = \\frac{L}{W} = \\frac{1}{\\cos\\phi}', detail:'How many g\'s the aircraft is pulling. In a 60° banked turn, n = 2. Load factor increases stall speed by √n. It ties performance directly to structural limits — maneuvering speed Va is defined as the speed at which CLmax is reached at limit load factor.', mistake:'Forgetting that stall speed changes in a turn. At 60° bank, stall speed increases by 41%. The flight envelope changes dynamically with manoeuvre.', interview:'What is the load factor in a 45° coordinated turn, and how does this affect stall speed?'},
        {id:'glide', label:'GLIDE RATIO', sub:'= L/D in power-off', r:2,c:'3/5', formula:'GR = \\frac{L}{D} \\bigg|_{power-off}', detail:'Horizontal distance per unit altitude in power-off glide. Equals L/D. Best glide speed is the minimum-drag speed. Above or below it, range is reduced. Wind correction is critical: headwind demands a higher glide speed.', mistake:'Confusing best glide speed (Vmd, maximises distance) with minimum sink speed (Vmp, maximises time aloft). They serve different emergency scenarios.', interview:'Given a 20 kt headwind, should you fly faster or slower than the published best glide speed, and by how much?'},
      ],
      edges:[['expow','roc',1],['exthrust','aoc',1],['roc','specrange'],['ld','specrange'],['ld','glide'],['loadf','roc'],['exthrust','aoc']]
    },
    {
      id:'l4', num:'04', title:'Operational Performance',
      sub:'Where theory meets the flight deck, the runway, and the fuel plan. These concepts live in the FCOM, on the PERF pages, and in every dispatcher\'s briefing pack.',
      nodes:[
        {id:'tkof', label:'TAKEOFF PERF', sub:'ground roll → 35 ft', r:1,c:'1/3', formula:'TODR \\propto \\frac{W^2}{\\rho\\,S\\,C_L\\,T}', detail:'Three simultaneous constraints govern takeoff: all-engine distance, accelerate-stop distance (ASD), and OEI climb gradient. The most restrictive limits the max takeoff weight. V1, Vr, and V2 are derived from these constraints.', mistake:'Assuming more thrust always helps. Flex/derate reduces thrust intentionally — the runway must be sufficient for the reduced-thrust case.', interview:'Explain the three simultaneous limiting cases for takeoff and which typically governs at MTOW.'},
        {id:'bfl', label:'BALANCED FIELD', sub:'TODR_OEI = ASD at V1', r:2,c:'1/3', tag:'work', formula:'BFL\\!: TOD_{OEI} = ASD \\text{ at } V_1', detail:'V1 is set such that the distance to stop equals the distance to continue on one engine. This maximises the allowable takeoff weight for a given runway. Airlines spend significant effort optimizing V1 to the specific runway, weight, and environmental conditions.', mistake:'Assuming V1 is always the balanced-field V1. V1 can be reduced for other reasons — the field then becomes stop-limited, not balanced.', interview:'What does a balanced field length mean operationally, and why would an airline optimize V1?'},
        {id:'oei', label:'OEI CLIMB', sub:'≥ 2.4% gradient req', r:1,c:'3/5', tag:'work', formula:'Grad_{OEI} = \\frac{T_{OEI}-D}{W} \\geq 2.4\\%', detail:'CS-25 / FAR-25 require a minimum 2.4% climb gradient at segment 2 with one engine inoperative. This constraint frequently limits RTOW more severely than runway length alone — especially at high altitude airports or on hot days.', mistake:'Thinking OEI performance only matters if an engine actually fails. It determines maximum permitted takeoff weight for every single departure.', interview:'Why does OEI segment 2 gradient set a harder operational constraint than actual runway length for many airports?'},
        {id:'svceil', label:'SERVICE CEILING', sub:'ROC = 100 fpm', r:2,c:'3/5', tag:'work', formula:'H_{svc}\\!: ROC = 100\\,\\text{fpm}', detail:'The altitude at which only 100 fpm of climb remains. Sets the practical upper limit for operations. OEI service ceiling is significantly lower and is critical for ETOPS routing over water or mountainous terrain.', mistake:'Confusing service ceiling with absolute ceiling. Service ceiling is operationally defined and reachable; absolute ceiling (ROC = 0) is theoretical.', interview:'How do weight and temperature affect service ceiling, and why does OEI service ceiling matter for route planning?'},
        {id:'breguet',label:'BREGUET RANGE', sub:'V, TSFC, L/D, ln(Wi/Wf)',r:3,c:'1/3', tag:'work', formula:'R = \\frac{V}{g\\cdot TSFC}\\cdot\\frac{L}{D}\\cdot\\ln\\!\\left(\\frac{W_i}{W_f}\\right)', detail:'The analytical range equation. Four levers: speed, engine efficiency (TSFC), aerodynamic efficiency (L/D), and fuel fraction. Every range improvement program traces directly to one of these four terms. A 1% improvement in L/D yields roughly 1% more range.', mistake:'Applying Breguet at constant altitude and speed to an aircraft that is step-climbing. The weight-ratio term must account for the actual flight profile.', interview:'Using the Breguet equation, which single parameter offers the largest potential range improvement and why?'},
        {id:'plrange',label:'PAYLOAD RANGE', sub:'the commercial DNA', r:3,c:'2/4', tag:'work', detail:'Three segments: MTOW-limited (full payload, short range), max-fuel-limited (payload traded for fuel beyond the knee), and ferry range (zero payload). The "knee" of the diagram is the design mission — where max payload meets max fuel volume.', mistake:'Assuming the aircraft can reach published maximum range with maximum payload. This is almost always impossible — payload must be reduced first.', interview:'Walk through the three segments of a transport aircraft payload-range diagram and what physically limits each.'},
        {id:'ci', label:'COST INDEX', sub:'C_time / C_fuel', r:3,c:'4/5', tag:'work', formula:'CI = \\frac{C_{time}}{C_{fuel}} \\;[\\text{kg/min}]', detail:'CI drives the ECON speed the FMS computes. CI = 0 gives maximum range cruise; CI = 999 gives maximum speed. For most airlines, CI sits between 20 and 80, depending on fuel price and schedule pressure. It is the most direct link between airline economics and aircraft speed.', mistake:'Assuming CI = 0 is always optimal. Time has real cost — crew, ownership, slot constraints. CI = 0 minimises fuel, not total trip cost.', interview:'An airline drops CI from 60 to 20 on all flights. What happens to fuel burn, flight time, and total trip cost?'},
      ],
      edges:[['tkof','bfl'],['oei','bfl',1],['roc','svceil',1],['ld','breguet',1],['specrange','breguet',1],['breguet','plrange'],['specrange','ci'],['bfl','plrange'],['svceil','plrange']]
    },
    {
      id:'l5', num:'05', title:'Limits of Performance',
      sub:'At high Mach numbers, compressibility rewrites the aerodynamic rules. A cascade of effects narrows the usable flight envelope until, at coffin corner, it closes to a point.',
      nodes:[
        {id:'mach', label:'MACH NUMBER', sub:'V / a — speed relative to sound',r:1,c:'2/4', formula:'M = \\frac{V}{a} = \\frac{V}{\\sqrt{\\gamma R T}}', detail:'The ratio of aircraft speed to the local speed of sound. As altitude increases, temperature and therefore the speed of sound decrease — so the same TAS gives a higher Mach number at altitude. This is why high-altitude cruise introduces compressibility effects not seen at low altitude.', mistake:'Assuming the speed of sound is constant. It varies with temperature, making Mach number dependent on altitude even at the same TAS.', interview:'An aircraft flies at 250 kt TAS at sea level and at FL350. Compare the Mach numbers and explain why they differ.'},
        {id:'mcrit', label:'CRITICAL MACH', sub:'first local M = 1.0', r:2,c:'1/3', detail:'The freestream Mach where the local airflow over the wing first reaches M = 1.0. Because the wing accelerates airflow, Mcrit < 1.0 for all subsonic aircraft. Wing sweep and supercritical sections are both designed to push Mcrit as high as possible.', mistake:'Confusing Mcrit with Mdd (drag divergence). Mcrit is when local M = 1 is first reached; Mdd is when drag increases rapidly — they differ by ~0.05 Mach.', interview:'How does wing sweep delay the critical Mach number, and what is the geometric reason?'},
        {id:'wavedrag',label:'WAVE DRAG', sub:'irreversible shock loss', r:2,c:'3/5', detail:'Energy lost irreversibly to shock-wave compression. Unlike induced or parasite drag, wave drag cannot be recovered. It is why supersonic flight is thermodynamically expensive and why the area rule (Whitcomb) was such a significant discovery.', mistake:'Treating wave drag as an on/off phenomenon at M = 1. It begins well below M = 1 wherever locally supersonic flow exists.', interview:'Explain the area rule and how it reduces wave drag on a transonic design.'},
        {id:'mdd', label:'DRAG DIVERGENCE',sub:'Mcrit + ~0.05', r:3,c:'1/3', tag:'work', formula:'\\left.\\frac{dC_D}{dM}\\right|_{M_{DD}} = 0.1', detail:'The Mach where wave drag increases sharply — the practical upper speed limit for efficient flight. MMO is set below Mdd with a safety margin. Supercritical airfoils and wing sweep together push Mdd to ~M0.85 for modern transports.', mistake:'Assuming Mdd = MMO. There must be margin between them for handling qualities, gust response, and control effectiveness.', interview:'Why must MMO be set significantly below Mdd, and what happens aerodynamically between MMO and Mdd?'},
        {id:'buffet', label:'BUFFET', sub:'shock-induced separation', r:3,c:'3/5', detail:'High-speed buffet is caused by oscillating separated flow behind the shock wave. It defines the top of the cruise speed envelope. Low-speed (stall) buffet defines the bottom. The usable cruise band lies between them — and at high altitude, this band narrows.', mistake:'Assuming buffet is only a high-speed phenomenon. Stall buffet and shock buffet are both "buffet" but arise from completely different physics.', interview:'What is the difference between low-speed stall buffet and high-speed shock buffet? What causes each?'},
        {id:'coffin', label:'COFFIN CORNER', sub:'Vstall = Vbuffet', r:4,c:'2/4', tag:'work', detail:'At extreme altitude, the IAS for stall rises (thinner air demands higher speed to generate the same lift force) while the IAS for buffet onset falls (compressibility effects arrive at lower IAS). These two speeds converge. At coffin corner altitude, flying any speed causes either stall or buffet — there is no safe speed.', mistake:'Thinking coffin corner is far above normal operations. For high-flying transport aircraft, it may be only a few thousand feet above FL410.', interview:'Explain coffin corner from first principles using both the low-speed and high-speed performance limits simultaneously.'},
      ],
      edges:[['mach','mcrit'],['mach','wavedrag'],['mcrit','mdd'],['wavedrag','mdd'],['mdd','buffet'],['buffet','coffin',1],['mcrit','buffet']]
    },
  ]
});
